import assert from "node:assert/strict";
import test, { afterEach } from "node:test";

import {
  assertPlannerGrounding,
  runAaliyahTask,
} from "../src/application/decision-engine/runAaliyahTask";
import { requiresApproval } from "../src/application/decision-engine/requiresApproval";
import { scoreCandidate } from "../src/application/decision-engine/scoreCandidate";
import { planTask } from "../src/application/planner/planTask";
import {
  llmPlanner,
  llmPlannerInternals,
} from "../src/application/planner/llmPlanner";
import {
  plannerClient,
  plannerClientInternals,
} from "../src/application/planner/plannerClient";
import { enforceTenantBoundary } from "../src/governance/enforceTenantBoundary";
import { rankEvidenceSources } from "../src/ranking/rankEvidenceSources";
import { buildEvidence, defaultEvidenceRankingPolicy } from "../src/services/buildEvidence";
import { detectContradictions } from "../src/services/detectContradictions";
import {
  ensureIdempotentExecution,
  idempotencyStoreInternals,
} from "../src/persistence/idempotencyStore";
import { retrieveEvidence } from "../src/services/retrieveEvidence";
import { selectCandidate } from "../src/services/selectCandidate";
import {
  executeIdempotent,
} from "../src/services/executeIdempotent";
import {
  verifyPostconditions,
} from "../src/services/verifyPostconditions";

process.env.AALIYAH_ALLOW_INMEMORY_IDEMPOTENCY = "true";

afterEach(() => {
  idempotencyStoreInternals.resetInMemory();
  llmPlannerInternals.callLLM = undefined;
  delete process.env.OPENAI_API_KEY;
});

function configureValidPlanner(): void {
  process.env.OPENAI_API_KEY = "test-only";
  plannerClientInternals.buildClient = () => ({
    responses: {
      create: async () => ({
        output_text: JSON.stringify({
          plannerVersion: "test-provider-v1",
          candidates: [{
            name: "provider_candidate",
            description: "Provider-generated candidate",
            args: {},
            rationale: "Generated by the configured test provider",
            evidenceRefs: [{
              sourceId: "workflow:current-state",
              rationale: "Current workflow state",
            }],
            goalFit: 95,
            evidenceQuality: 95,
            policyFit: 95,
            expectedValue: 90,
            reversibility: 90,
            downsideRisk: 5,
            ambiguity: 5,
            contradictions: 0,
            blockers: [],
          }],
          rejectedAlternatives: [],
        }),
      }),
    },
  }) as never;
}

test("scoreCandidate rewards fit and penalizes risk", () => {
  const score = scoreCandidate({
    name: "candidate",
    description: "test",
    args: {},
    goalFit: 90,
    evidenceQuality: 85,
    policyFit: 95,
    expectedValue: 70,
    reversibility: 80,
    downsideRisk: 10,
    ambiguity: 15,
    contradictions: 0,
    blockers: [],
  });

  assert.equal(score, 75);
  assert.equal(requiresApproval("A4_IRREVERSIBLE", score, 40), true);
  assert.equal(requiresApproval("A0_READ", score, 40), false);
});

test("runAaliyahTask rejects unavailable synthetic workflow evidence", async () => {
  await assert.rejects(
    () => runAaliyahTask({
      taskId: "550e8400-e29b-41d4-a716-446655440000",
      tenantId: "tenant_123",
      userId: "user_123",
      taskType: "write",
      riskTier: "A2_WRITE_APPROVED",
      requestedOutcome: "Send an external message",
      inputs: { channel: "email" },
      requiredSources: ["source_123"],
      constraints: [],
      createdAt: "2026-04-18T12:00:00.000Z",
    }),
    /No evidence sources available/,
  );
});

test("shadow mode cannot bypass evidence rejection", async () => {
  process.env.AALIYAH_SHADOW_MODE = "true";

  try {
    await assert.rejects(
      () => runAaliyahTask({
        taskId: "550e8400-e29b-41d4-a716-446655440099",
        tenantId: "tenant_123",
        userId: "user_123",
        taskType: "decision",
        riskTier: "A1_DRAFT",
        requestedOutcome: "Recommend next action",
        inputs: {},
        requiredSources: [],
        constraints: [],
        createdAt: "2026-04-18T12:00:00.000Z",
      }),
      /No evidence sources available/,
    );
  } finally {
    delete process.env.AALIYAH_SHADOW_MODE;
  }
});

test("deterministic planner rejects fixed-score production decisions", async () => {
  const evidence = await buildEvidence({
    taskId: "550e8400-e29b-41d4-a716-446655440000",
    tenantId: "tenant_123",
    userId: "user_123",
    taskType: "decision",
    riskTier: "A1_DRAFT",
    requestedOutcome: "Choose the best next action",
    requiredSources: ["crm:account", "gmail:thread"],
    constraints: [],
  });

  const rankedEvidence = rankEvidenceSources(
    evidence,
    defaultEvidenceRankingPolicy(),
  );

  await assert.rejects(
    () => planTask({
      request: {
        task: {
        taskId: "550e8400-e29b-41d4-a716-446655440000",
        tenantId: "tenant_123",
        userId: "user_123",
        taskType: "decision",
        riskTier: "A1_DRAFT",
        requestedOutcome: "Choose the best next action",
        inputs: {},
        constraints: [],
        requiredSources: ["crm:account", "gmail:thread"],
        createdAt: "2026-04-18T12:00:00.000Z",
        },
        policy: {
        planningMode: "multi_option",
        maxCandidates: 3,
        requireEvidenceForAllCandidates: true,
        requireDissentCandidate: true,
        minimumScoreThreshold: 75,
        minimumMarginThreshold: 8,
        },
        availableTools: [],
        evidenceBundleId: evidence.bundleId,
      },
      rankedEvidence,
    }),
    /deterministic_planner_prohibited_in_production/,
  );
});

test("llmPlanner fails explicitly when no provider is wired", async () => {
  await assert.rejects(
    () => llmPlanner({
      task: {
        taskId: "550e8400-e29b-41d4-a716-446655440002",
        tenantId: "tenant_123",
        userId: "user_123",
        taskType: "decision",
        riskTier: "A1_DRAFT",
        requestedOutcome: "Recommend the next move",
        inputs: {},
        constraints: [],
        requiredSources: [],
        createdAt: "2026-04-18T12:00:00.000Z",
      },
      policy: {
        planningMode: "multi_option",
        maxCandidates: 2,
        requireEvidenceForAllCandidates: true,
        requireDissentCandidate: true,
        minimumScoreThreshold: 75,
        minimumMarginThreshold: 8,
      },
      availableTools: [],
    }, []),
    /planner_provider_unavailable/,
  );
});

test("llmPlanner fails closed on malformed provider output", async () => {
  llmPlannerInternals.callLLM = async () => "{not-json";
  await assert.rejects(
    () => llmPlanner({
      task: {
        taskId: "550e8400-e29b-41d4-a716-446655440003",
        tenantId: "tenant_123",
        userId: "user_123",
        taskType: "decision",
        riskTier: "A1_DRAFT",
        requestedOutcome: "Recommend the next move",
        inputs: {},
        constraints: [],
        requiredSources: [],
        createdAt: "2026-04-18T12:00:00.000Z",
      },
      policy: {
        planningMode: "multi_option",
        maxCandidates: 2,
        requireEvidenceForAllCandidates: true,
        requireDissentCandidate: true,
        minimumScoreThreshold: 75,
        minimumMarginThreshold: 8,
      },
      availableTools: [],
    }, []),
    /LLM returned invalid JSON/,
  );
});

test("detectContradictions flags conflicting evidence excerpts", () => {
  const processed = detectContradictions([
    {
      sourceId: "1",
      sourceType: "manual",
      title: "Account status",
      excerpt: "Active",
      trustLevel: "high",
      freshness: "current",
      relevanceScore: 80,
      authorityScore: 80,
      recencyScore: 80,
      contradictionFlags: [],
      tags: [],
      retrievedAt: "2026-04-18T12:00:00.000Z",
    },
    {
      sourceId: "2",
      sourceType: "manual",
      title: "Account status",
      excerpt: "Suspended",
      trustLevel: "high",
      freshness: "current",
      relevanceScore: 80,
      authorityScore: 80,
      recencyScore: 80,
      contradictionFlags: [],
      tags: [],
      retrievedAt: "2026-04-18T12:00:00.000Z",
    },
  ]);

  assert.deepEqual(processed[0]?.contradictionFlags ?? [], []);
  assert.deepEqual(processed[1]?.contradictionFlags ?? [], ["content_mismatch"]);
});

test("plannerClient reports explicit failure when unconfigured", async () => {
  await assert.rejects(() => plannerClient({
    task: {
      taskId: "550e8400-e29b-41d4-a716-446655440010",
      tenantId: "tenant_123",
      userId: "user_123",
      taskType: "decision",
      riskTier: "A1_DRAFT",
      requestedOutcome: "Decide what to do next",
      inputs: {},
      constraints: [],
      requiredSources: [],
      createdAt: "2026-04-18T12:00:00.000Z",
    },
    policy: {
      planningMode: "multi_option",
      maxCandidates: 3,
      requireEvidenceForAllCandidates: true,
      requireDissentCandidate: true,
      minimumScoreThreshold: 75,
      minimumMarginThreshold: 8,
    },
    availableTools: [],
  }), /planner_failed_closed:unconfigured_client/);
});

test("plannerClient fails closed on malformed provider output", async () => {
  process.env.OPENAI_API_KEY = "test-only";
  plannerClientInternals.buildClient = () => ({
    responses: {
      create: async () => ({ output_text: "{not-json" }),
    },
  }) as never;

  await assert.rejects(
    () => plannerClient({
      task: {
        taskId: "550e8400-e29b-41d4-a716-446655440011",
        tenantId: "tenant_123",
        userId: "user_123",
        taskType: "decision",
        riskTier: "A1_DRAFT",
        requestedOutcome: "Decide what to do next",
        inputs: {},
        constraints: [],
        requiredSources: [],
        createdAt: "2026-04-18T12:00:00.000Z",
      },
      policy: {
        planningMode: "multi_option",
        maxCandidates: 3,
        requireEvidenceForAllCandidates: true,
        requireDissentCandidate: true,
        minimumScoreThreshold: 75,
        minimumMarginThreshold: 8,
      },
      availableTools: [],
    }),
    /planner_failed_closed:invalid_json/,
  );
});

test("planner proposals reject invented evidence and unsupported tools", () => {
  const baseCandidate = {
    name: "proposal",
    description: "Provider proposal",
    args: {},
    rationale: "Proposal only",
    evidenceRefs: [{
      sourceId: "invented:source",
      rationale: "Invented reference",
    }],
    goalFit: 100,
    evidenceQuality: 100,
    policyFit: 100,
    expectedValue: 100,
    reversibility: 100,
    downsideRisk: 0,
    ambiguity: 0,
    contradictions: 0,
    blockers: [],
  };
  assert.throws(
    () => assertPlannerGrounding({
      plannerVersion: "test",
      candidates: [baseCandidate],
      rejectedAlternatives: [],
    }, new Set(["real:source"]), []),
    /planner_evidence_reference_ungrounded/,
  );

  assert.throws(
    () => assertPlannerGrounding({
      plannerVersion: "test",
      candidates: [{
        ...baseCandidate,
        args: { tool: "email.send" },
        evidenceRefs: [{
          sourceId: "real:source",
          rationale: "Grounded reference",
        }],
      }],
      rejectedAlternatives: [],
    }, new Set(["real:source"]), []),
    /planner_tool_unsupported/,
  );
});

const executionCandidate = {
  name: "real_action",
  description: "Execute a real action",
  args: {},
  goalFit: 80,
  evidenceQuality: 80,
  policyFit: 80,
  expectedValue: 80,
  reversibility: 80,
  downsideRisk: 10,
  ambiguity: 10,
  contradictions: 0,
  blockers: [],
};

test("no executor configured never reports success", async () => {
  await assert.rejects(
    () => executeIdempotent(executionCandidate, {
      tenantId: "tenant_123",
      workspaceId: "tenant_123:default",
      taskId: "550e8400-e29b-41d4-a716-446655440020",
      idempotencyKey: "idem-20",
    }),
    /execution_capability_unavailable/,
  );
});

test("executor throw and ambiguous result never report success", async () => {
  const throwingExecutor = async () => {
    throw new Error("connector failed");
  };
  await assert.rejects(
    () => executeIdempotent(executionCandidate, {
      tenantId: "tenant_123",
      workspaceId: "tenant_123:default",
      taskId: "550e8400-e29b-41d4-a716-446655440021",
      idempotencyKey: "idem-21",
    }, throwingExecutor),
    /connector failed/,
  );

  const ambiguousExecutor = async () => ({ success: true });
  await assert.rejects(
    () => executeIdempotent(executionCandidate, {
      tenantId: "tenant_123",
      workspaceId: "tenant_123:default",
      taskId: "550e8400-e29b-41d4-a716-446655440021",
      idempotencyKey: "idem-21",
    }, ambiguousExecutor),
    /executor_result_ambiguous/,
  );
});

test("execution remains unsuccessful until independent read-back verifies it", async () => {
  const executor = async (_candidate: unknown, options: {
    taskId: string;
    idempotencyKey: string;
  }) => ({
    success: true,
    tenantId: "tenant_123",
    workspaceId: "tenant_123:default",
    taskId: options.taskId,
    idempotencyKey: options.idempotencyKey,
    executionReceiptId: "provider-execution-1",
    executorId: "provider-executor-v1",
    externalRefs: ["provider:receipt-1"],
  });
  const result = await executeIdempotent(executionCandidate, {
    tenantId: "tenant_123",
    workspaceId: "tenant_123:default",
    taskId: "550e8400-e29b-41d4-a716-446655440022",
    idempotencyKey: "idem-22",
  }, executor);
  assert.equal(result.success, false);
  assert.equal(result.postconditionsMet, false);

  const task = {
    taskId: result.taskId,
    tenantId: "tenant_123",
    userId: "user_123",
    taskType: "decision" as const,
    riskTier: "A1_DRAFT" as const,
    requestedOutcome: "Verify action",
    inputs: {},
    constraints: [],
    requiredSources: [],
    createdAt: "2026-04-18T12:00:00.000Z",
  };
  await assert.rejects(
    () => verifyPostconditions(task, result, { nowMs: Date.now() }),
    /postcondition_verifier_unavailable/,
  );

  const mismatchVerifier = async () => ({
    contractVersion: "aaliyah.postcondition-verification/v1",
    verified: false,
    tenantId: result.tenantId,
    workspaceId: result.workspaceId,
    taskId: task.taskId,
    idempotencyKey: result.idempotencyKey,
    executionReceiptId: result.executionReceiptId,
    executorId: result.executorId,
    externalRefs: ["provider:receipt-1"],
    verifierId: "test-readback",
    verificationMethod: "independent_readback",
    verifiedAt: new Date().toISOString(),
    reason: "read-back mismatch",
  });
  await assert.rejects(
    () => verifyPostconditions(task, result, { nowMs: Date.now() }, mismatchVerifier),
    /Invalid input/,
  );

  const partialVerifier = async () => ({
    contractVersion: "aaliyah.postcondition-verification/v1",
    verified: true,
    tenantId: result.tenantId,
    workspaceId: result.workspaceId,
    taskId: task.taskId,
    idempotencyKey: result.idempotencyKey,
    executionReceiptId: result.executionReceiptId,
    executorId: result.executorId,
    externalRefs: ["provider:different-receipt"],
    verifierId: "test-readback",
    verificationMethod: "independent_readback",
    verifiedAt: new Date().toISOString(),
  });
  await assert.rejects(
    () => verifyPostconditions(task, result, { nowMs: Date.now() }, partialVerifier),
    /postcondition_verification_ref_coverage_invalid/,
  );

  const exactVerifier = async () => ({
    contractVersion: "aaliyah.postcondition-verification/v1",
    verified: true,
    tenantId: result.tenantId,
    workspaceId: result.workspaceId,
    taskId: task.taskId,
    idempotencyKey: result.idempotencyKey,
    executionReceiptId: result.executionReceiptId,
    executorId: result.executorId,
    externalRefs: ["provider:receipt-1"],
    verifierId: "test-readback",
    verificationMethod: "independent_readback",
    verifiedAt: new Date().toISOString(),
  });
  assert.equal(
    (await verifyPostconditions(task, result, { nowMs: Date.now() }, exactVerifier)).verified,
    true,
  );

  const selfVerifier = async () => ({
    ...(await exactVerifier()),
    verifierId: result.executorId,
  });
  await assert.rejects(
    () => verifyPostconditions(task, result, { nowMs: Date.now() }, selfVerifier),
    /verifier must be independent from executor/,
  );

  const forgedVerifier = async () => ({
    ...(await exactVerifier()),
    taskId: "550e8400-e29b-41d4-a716-446655440999",
  });
  await assert.rejects(
    () => verifyPostconditions(task, result, { nowMs: Date.now() }, forgedVerifier),
    /postcondition_verification_binding_invalid/,
  );

  const staleVerifier = async () => ({
    ...(await exactVerifier()),
    verifiedAt: "2020-01-01T00:00:00.000Z",
  });
  await assert.rejects(
    () => verifyPostconditions(task, result, { nowMs: Date.now() }, staleVerifier),
    /postcondition_verification_receipt_stale/,
  );
});

test("runAaliyahTask has no production executor or verifier seam", async () => {
  const task = {
    taskId: "550e8400-e29b-41d4-a716-446655440023",
    tenantId: "tenant_123",
    userId: "user_123",
    taskType: "decision" as const,
    riskTier: "A1_DRAFT" as const,
    requestedOutcome: "Perform and verify action",
    inputs: {},
    constraints: [],
    requiredSources: [],
    createdAt: "2026-04-18T12:00:00.000Z",
  };

  await assert.rejects(() => runAaliyahTask(task), /No evidence sources available/);
  await assert.rejects(() => runAaliyahTask(task), /No evidence sources available/);
});

test("retrieveEvidence returns brokered evidence with a bundle id", async () => {
  const bundle = await retrieveEvidence({
    tenantId: "tenant_123",
    userId: "user_123",
    query: "Find latest client state",
    connectors: ["gmail", "calendar", "workflow_state"],
    limit: 10,
  });

  assert.equal(bundle.sourceCount, 0);
  assert.match(bundle.bundleId, /^bundle:tenant_123:/);
});

test("ensureIdempotentExecution rejects duplicate in-progress requests", async () => {
  await ensureIdempotentExecution("idem-123", { action: "send" }, "write");

  await assert.rejects(
    () => ensureIdempotentExecution("idem-123", { action: "send" }, "write"),
    /Idempotent request already in progress/,
  );
});

test("enforceTenantBoundary rejects records from another tenant", () => {
  assert.throws(
    () =>
      enforceTenantBoundary("tenant_123", [
        { tenantId: "tenant_123" },
        { tenantId: "tenant_other" },
      ]),
    /Tenant boundary violation detected/,
  );
});
