/**
 * THE CATALOG EFFECT OF EVERY MIGRATION, DERIVED BY EXECUTION.
 *
 *   node --require ts-node/register scripts/migration-evidence.ts --write   regenerate
 *   node --require ts-node/register scripts/migration-evidence.ts --check   exit 1 on drift
 *
 * Creates a scratch database on the server named by AALIYAH_TEST_DATABASE_URL,
 * creates the ledger exactly as the runner does, then applies every
 * migration's SQL in order — each in its own transaction, NOT through
 * runMailMigrations, so the evidence is what the SQL does and not what the
 * runner believes — snapshotting the catalog after each. A migration's
 * evidence is the difference: keys it created or changed, keys it removed.
 * The runner reads the schema back against this (migrationCatalog.ts).
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { Pool } from "pg";

import { readCatalog, type MigrationCatalogEvidence } from "../src/persistence/postgres/migrationCatalog";
import {
  createLedgerToleratingARace,
  migrationDigest,
  MIGRATIONS,
} from "../src/persistence/postgres/migrations";
import { boundedQuery, MIGRATION_BOUNDS } from "../src/persistence/postgres/pool";

export const EVIDENCE_FILE = path.resolve(__dirname, "../src/persistence/postgres/migrationEvidence.generated.ts");

export async function deriveMigrationEvidence(serverUrl: string): Promise<Record<string, MigrationCatalogEvidence>> {
  const name = `aaliyah_migration_evidence_${process.pid}`;
  const admin = new Pool({ connectionString: serverUrl, max: 1 });
  admin.on("error", () => undefined);
  await admin.query(`DROP DATABASE IF EXISTS ${name} WITH (FORCE)`);
  await admin.query(`CREATE DATABASE ${name}`);
  const pool = new Pool({ connectionString: serverUrl.replace(/\/[^/?]+(\?.*)?$/, `/${name}`), max: 1 });
  pool.on("error", () => undefined);
  const evidence: Record<string, MigrationCatalogEvidence> = {};
  try {
    const client = await pool.connect();
    try {
      const bounded = boundedQuery(client, MIGRATION_BOUNDS.queryTimeoutMs);
      await createLedgerToleratingARace(bounded);
      let before = await readCatalog(bounded);
      for (const migration of MIGRATIONS) {
        await bounded("BEGIN");
        await bounded(migration.sql);
        await bounded("COMMIT");
        const after = await readCatalog(bounded);
        const set: Record<string, string> = {};
        for (const [key, fp] of after) if (before.get(key) !== fp) set[key] = fp;
        const drop = [...before.keys()].filter((key) => !after.has(key)).sort();
        evidence[migration.id] = { sqlDigest: migrationDigest(migration.sql), set, drop };
        before = after;
      }
    } finally {
      client.release(true);
    }
  } finally {
    await pool.end().catch(() => undefined);
    await admin.query(`DROP DATABASE IF EXISTS ${name} WITH (FORCE)`).catch(() => undefined);
    await admin.end().catch(() => undefined);
  }
  return evidence;
}

export function renderEvidence(evidence: Record<string, MigrationCatalogEvidence>): string {
  const body = Object.keys(evidence)
    .map((id) => {
      const e = evidence[id]!;
      const set = Object.keys(e.set)
        .sort()
        .map((k) => `      ${JSON.stringify(k)}: ${JSON.stringify(e.set[k])},`)
        .join("\n");
      const drop = e.drop.map((k) => `      ${JSON.stringify(k)},`).join("\n");
      return `  ${JSON.stringify(id)}: {\n    sqlDigest: ${JSON.stringify(e.sqlDigest)},\n    set: {\n${set}\n    },\n    drop: [\n${drop}\n    ],\n  },`;
    })
    .join("\n");
  return `/**
 * GENERATED by scripts/migration-evidence.ts --write. DO NOT EDIT BY HAND.
 *
 * Each migration's catalog effect, derived by applying every migration's SQL in
 * order to an empty database and diffing the catalog after each. The migration
 * runner reads the schema back against this (migrationCatalog.ts), and refuses
 * a build whose evidence was generated from different SQL. A test regenerates
 * it and fails on any difference.
 */
import type { MigrationCatalogEvidence } from "./migrationCatalog";

export const MIGRATION_CATALOG_EVIDENCE: Readonly<Record<string, MigrationCatalogEvidence>> = {
${body}
};
`;
}

if (require.main === module) {
  const mode = process.argv[2];
  const url = process.env.AALIYAH_TEST_DATABASE_URL;
  if ((mode !== "--write" && mode !== "--check") || !url) {
    process.stderr.write("usage: AALIYAH_TEST_DATABASE_URL=... migration-evidence.ts --write|--check\n");
    process.exit(2);
  }
  deriveMigrationEvidence(url)
    .then((evidence) => {
      const rendered = renderEvidence(evidence);
      if (mode === "--write") {
        fs.writeFileSync(EVIDENCE_FILE, rendered);
        process.stdout.write(`wrote ${Object.keys(evidence).length} migrations to ${EVIDENCE_FILE}\n`);
      } else if (fs.readFileSync(EVIDENCE_FILE, "utf8") !== rendered) {
        process.stderr.write("migration evidence DRIFT: the committed file is not what the SQL does\n");
        process.exit(1);
      } else {
        process.stdout.write("migration evidence matches the SQL\n");
      }
    })
    .catch((error) => {
      process.stderr.write(`${error?.stack ?? error}\n`);
      process.exit(1);
    });
}
